apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: panel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: panel
    spec:
      containers:
        - image: gcr.io/airglide-166614/panel:1.1.0-SNAPSHOT
          name: panel
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 200M
          ports:
            - containerPort: 80
